### ISSUE TITLE
앵커 링크로 접근 시 표시 위치 오류

### ISSUE THREAD

**Issue by mozodev** [ictact-coop/docs#3]
https://ictact-coop.github.io/docs/docs/constitution/#제42조이사회의-의결사항

예를 들어 저렇게 접근했을 때 42조가 아니고 49조 쯤이 보이네요.
사이드바에 스크롤바를 강제로 높이를 줘서 상하로 스크롤 되게 했더니 이런 문제가 발생한 듯

원래 스크롤스파이로 돌아갈까요?

**Comment by data-ictact** [comment]
https://github.com/ictact-coop/docs/commit/c4e3881e1e912f67bcbd0a1c98bba79402f794bb
